# Scraping with Pandas

In [2]:
import pandas as pd

We can use the `read_html` function in Pandas to automatically scrape any tabular data from a page.

In [3]:
url = 'https://vgsales.fandom.com/wiki/List_of_best-selling_video_games'

In [4]:
tables = pd.read_html(url)
len(tables)

3

#### What we get in return is a list of dataframes for any tabular data that Pandas found.

In [5]:
type(tables)

list

#### We can slice off any of those dataframes that we want using normal indexing.

In [6]:
df = tables[0]
df

,Title,Release year,Genre,Platform(s),Sales(million units),Source(s)
0,Minecraft,2009,Sandbox,"PC, Xbox 360 PlayStation 3, Various",238.000,[n 1]
1,Grand Theft Auto V,2013,Action Adventure,"PC, PlayStation 3, PlayStation 4, Xbox 360, Xb...",135.000,NaN
2,Wii Sports,2006,Sports,Wii,82.900,[2]
3,Super Mario Bros.,1985,Platformer,"NES, Various",63.330,[12]
4,Pokémon Red/Green/Blue/Yellow,1996,RPG,"Game Boy, Game Boy Advance, Virtual Console",59.520,[5]
5,PlayerUnknown's Battlegrounds,2017,Battle Royale,"PC, PlayStation 4, Xbox One",70.000,[13][14]
6,Sonic the Hedgehog,1991,Platformer,"Mega Drive, Master System, Various",44.146,[15]
7,Wii Fit,2007,Fitness,Wii,43.800,[n 2]
8,Pokémon Gold/Silver/Crystal,1999,RPG,"Game Boy Color, Nintendo DS",42.210,[5]
9,Super Mario Bros. 3,1988,Platformer,"NES, Various",39.520,[12]
10,Super Mario Bros. 2,1986,Platformer,"FDS, NES, Various",38.390,[12]
11,Mario Kart Wii,2008,Racing,Wii,37.100,[2]
12,Pokémon Ruby/Sapphire/Emerald,2002,RPG,"GBA, 3DS",36.600,[5]
13,Super Mario World,1990,Platformer,"Super NES, Various",34.183,[12]
14,Wii Sports Resort,2009,Sports,Wii,33.080,[2]
15,New Super Mario Bros.,2006,Platformer,Nintendo DS,30.800,[16][17]
16,New Super Mario Bros. Wii,2009,Platformer,Wii,30.200,[2]
17,Duck Hunt,1984,Lightgun Shooter,NES,28.310,[6]
18,Wii Play,2006,Party,Wii,28.020,[2]
19,Grand Theft Auto: San Andreas,2004,Action Adventure,"PC, PlayStation 2, PlayStation 3 (PSN), Xbox, ...",27.500,[18]
20,Call of Duty: Modern Warfare 3,2011,FPS,"PC, Xbox 360, PlayStation 3, Wii",26.500,[19][20]
21,Pokémon Diamond/Pearl/Platinum,2006,RPG,Nintendo DS,25.270,[5]
22,Grand Theft Auto IV,2008,Action Adventure,"PC, PlayStation 3, Xbox 360",25.000,[21][22]
23,Call of Duty: Black Ops,2010,FPS,"PC, PlayStation 3, Xbox 360, Wii, Nintendo DS",25.000,[23][24][25]
24,Kinect Adventures,2010,Sports,Xbox 360,24.000,[26]
25,Call of Duty: Black Ops II,2012,FPS,"PC, PlayStation 3, Xbox 360",24.000,[27]
26,FIFA 18,2017,Sports,"PC, PlayStation 3, PlayStation 4, Xbox 360, Xb...",24.000,[28]
27,Nintendogs,2005,Sim,Nintendo DS,23.960,[4]
28,Pokémon Sun and Moon,2016,RPG,Nintendo 3DS,23.610,[5]
29,Mario Kart DS,2005,Racing,Nintendo DS,23.600,[4]
30,Super Mario 64,1996,Platformer,"N64, Nintendo DS",23.240,[12]
31,Call of Duty: Modern Warfare 2,2009,FPS,"PC, Xbox 360, PlayStation 3",22.000,[23]
32,Street Fighter II,1991,Fighting,"Super NES, Mega Drive, Various",20.780,[29]
33,Call of Duty: WWII,2017,FPS,"PC, PlayStation 4, Xbox One",20.620,[30]
34,Mario Kart 8,2014,Racing,"Wii U, Switch",20.160,[31]
35,Frogger,1981,Action,"Arcade, Various",20.000,[32]
36,Terraria,2011,Platformer,"PC, Various",20.000,[33]
37,The Sims 2,2004,Sim,"PC, Various",20.000,[34]
38,The Elder Scrolls V: Skyrim,2011,Action RPG,"PC, Xbox 360, PlayStation 3",20.000,[35]
39,Brain Age,2005,Puzzle,Nintendo DS,19.010,[16]
40,Call of Duty: Ghosts,2013,FPS,"PC, Xbox 360, Xbox One, PlayStation 3, PlaySta...",19.000,[36]
41,Super Mario Land,1989,Platformer,"Game Boy, Game Boy Color",18.371,[12]
42,Grand Theft Auto: Vice City,2002,Action Adventure,"PC, Playstation 2, Xbox",17.500,[37]
43,Gran Turismo 3: A-Spec,2001,Racing Sim,Playstation 2,16.450,[38]
44,Pokémon X and Y,2013,RPG,Nintendo 3DS,16.290,[5]
45,Gran Turismo 5,2010,Racing Sim,Playstation 3,16.010,[38]
46,The Sims,2000,Life Sim,"PC, Mac OS",16.000,[39]
47,Call of Duty 4: Modern Warfare,2007,FPS,"PC, Xbox 360, Mac OS X, PlayStation 3, Wii",15.700,[19][40]
48,Call of Duty: World at War,2008,FPS,"PC, Xbox 360, PlayStation 3, Wii",15.700,[19]
49,Pokémon Black and White,2010,RPG,Nintendo DS,15.640,[5]
50,Diablo III,2012,RPG,"PC, Mac OS X, Xbox 360, PlayStation 3",15.000,[41][42]

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Title                 51 non-null     object
 1   Release year          51 non-null     int64
 2   Genre                 51 non-null     object
 3   Platform(s)           51 non-null     object
 4   Sales(million units)  51 non-null     float64
 5   Source(s)             50 non-null     object
dtypes: float64(1), int64(1), object(4)
memory usage: 2.5+ KB

#### Slipt column values into two separate columns

#### Drop a column

In [8]:
df = df.drop(['Source(s)'], axis=1)
df.head()

,Title,Release year,Genre,Platform(s),Sales(million units)
0,Minecraft,2009,Sandbox,"PC, Xbox 360 PlayStation 3, Various",238.00
1,Grand Theft Auto V,2013,Action Adventure,"PC, PlayStation 3, PlayStation 4, Xbox 360, Xb...",135.00
2,Wii Sports,2006,Sports,Wii,82.90
3,Super Mario Bros.,1985,Platformer,"NES, Various",63.33
4,Pokémon Red/Green/Blue/Yellow,1996,RPG,"Game Boy, Game Boy Advance, Virtual Console",59.52

In [42]:
df.rename(columns = {'Title':'title','Genre':'genre', 'Platform(s)':'platform', 'release_year':'release_date', 'Sales(million units)': 'units_sold'}, inplace = True)

In [43]:
df.head()

,title,release_date,genre,platform,units_sold
0,Minecraft,2009,Sandbox,"PC, Xbox 360 PlayStation 3, Various",238.00
1,Grand Theft Auto V,2013,Action Adventure,"PC, PlayStation 3, PlayStation 4, Xbox 360, Xb...",135.00
2,Wii Sports,2006,Sports,Wii,82.90
3,Super Mario Bros.,1985,Platformer,"NES, Various",63.33
4,Pokémon Red/Green/Blue/Yellow,1996,RPG,"Game Boy, Game Boy Advance, Virtual Console",59.52

In [44]:
df.to_csv(r'C:\Users\malac\SMU\Project 2\vg_sales_wiki.csv', index=False)

In [45]:
cols = [0, 4]


game_df = df[df.columns[cols]]
game_df

                             title  units_sold
0                        Minecraft     238.000
1               Grand Theft Auto V     135.000
2                       Wii Sports      82.900
3                Super Mario Bros.      63.330
4    Pokémon Red/Green/Blue/Yellow      59.520
5    PlayerUnknown's Battlegrounds      70.000
6               Sonic the Hedgehog      44.146
7                          Wii Fit      43.800
8      Pokémon Gold/Silver/Crystal      42.210
9              Super Mario Bros. 3      39.520
10             Super Mario Bros. 2      38.390
11                  Mario Kart Wii      37.100
12   Pokémon Ruby/Sapphire/Emerald      36.600
13               Super Mario World      34.183
14               Wii Sports Resort      33.080
15           New Super Mario Bros.      30.800
16       New Super Mario Bros. Wii      30.200
17                       Duck Hunt      28.310
18                        Wii Play      28.020
19   Grand Theft Auto: San Andreas      27.500
20  Call of Duty: Modern Warfare 3      26.500
21  Pokémon Diamond/Pearl/Platinum      25.270
22             Grand Theft Auto IV      25.000
23         Call of Duty: Black Ops      25.000
24               Kinect Adventures      24.000
25      Call of Duty: Black Ops II      24.000
26                         FIFA 18      24.000
27                      Nintendogs      23.960
28            Pokémon Sun and Moon      23.610
29                   Mario Kart DS      23.600
30                  Super Mario 64      23.240
31  Call of Duty: Modern Warfare 2      22.000
32               Street Fighter II      20.780
33              Call of Duty: WWII      20.620
34                    Mario Kart 8      20.160
35                         Frogger      20.000
36                        Terraria      20.000
37                      The Sims 2      20.000
38     The Elder Scrolls V: Skyrim      20.000
39                       Brain Age      19.010
40            Call of Duty: Ghosts      19.000
41                Super Mario Land      18.371
42     Grand Theft Auto: Vice City      17.500
43          Gran Turismo 3: A-Spec      16.450
44                 Pokémon X and Y      16.290
45                  Gran Turismo 5      16.010
46                        The Sims      16.000
47  Call of Duty 4: Modern Warfare      15.700
48      Call of Duty: World at War      15.700
49         Pokémon Black and White      15.640
50                      Diablo III      15.000

In [46]:
df[df["genre"].duplicated()]

,title,release_date,genre,platform,units_sold
6,Sonic the Hedgehog,1991,Platformer,"Mega Drive, Master System, Various",44.146
8,Pokémon Gold/Silver/Crystal,1999,RPG,"Game Boy Color, Nintendo DS",42.210
9,Super Mario Bros. 3,1988,Platformer,"NES, Various",39.520
10,Super Mario Bros. 2,1986,Platformer,"FDS, NES, Various",38.390
12,Pokémon Ruby/Sapphire/Emerald,2002,RPG,"GBA, 3DS",36.600
13,Super Mario World,1990,Platformer,"Super NES, Various",34.183
14,Wii Sports Resort,2009,Sports,Wii,33.080
15,New Super Mario Bros.,2006,Platformer,Nintendo DS,30.800
16,New Super Mario Bros. Wii,2009,Platformer,Wii,30.200
19,Grand Theft Auto: San Andreas,2004,Action Adventure,"PC, PlayStation 2, PlayStation 3 (PSN), Xbox, ...",27.500
21,Pokémon Diamond/Pearl/Platinum,2006,RPG,Nintendo DS,25.270
22,Grand Theft Auto IV,2008,Action Adventure,"PC, PlayStation 3, Xbox 360",25.000
23,Call of Duty: Black Ops,2010,FPS,"PC, PlayStation 3, Xbox 360, Wii, Nintendo DS",25.000
24,Kinect Adventures,2010,Sports,Xbox 360,24.000
25,Call of Duty: Black Ops II,2012,FPS,"PC, PlayStation 3, Xbox 360",24.000
26,FIFA 18,2017,Sports,"PC, PlayStation 3, PlayStation 4, Xbox 360, Xb...",24.000
28,Pokémon Sun and Moon,2016,RPG,Nintendo 3DS,23.610
29,Mario Kart DS,2005,Racing,Nintendo DS,23.600
30,Super Mario 64,1996,Platformer,"N64, Nintendo DS",23.240
31,Call of Duty: Modern Warfare 2,2009,FPS,"PC, Xbox 360, PlayStation 3",22.000
33,Call of Duty: WWII,2017,FPS,"PC, PlayStation 4, Xbox One",20.620
34,Mario Kart 8,2014,Racing,"Wii U, Switch",20.160
36,Terraria,2011,Platformer,"PC, Various",20.000
37,The Sims 2,2004,Sim,"PC, Various",20.000
40,Call of Duty: Ghosts,2013,FPS,"PC, Xbox 360, Xbox One, PlayStation 3, PlaySta...",19.000
41,Super Mario Land,1989,Platformer,"Game Boy, Game Boy Color",18.371
42,Grand Theft Auto: Vice City,2002,Action Adventure,"PC, Playstation 2, Xbox",17.500
44,Pokémon X and Y,2013,RPG,Nintendo 3DS,16.290
45,Gran Turismo 5,2010,Racing Sim,Playstation 3,16.010
47,Call of Duty 4: Modern Warfare,2007,FPS,"PC, Xbox 360, Mac OS X, PlayStation 3, Wii",15.700
48,Call of Duty: World at War,2008,FPS,"PC, Xbox 360, PlayStation 3, Wii",15.700
49,Pokémon Black and White,2010,RPG,Nintendo DS,15.640
50,Diablo III,2012,RPG,"PC, Mac OS X, Xbox 360, PlayStation 3",15.000

In [47]:
genre_list = df.genre.unique()
genre_list

array(['Sandbox', 'Action Adventure', 'Sports', 'Platformer', 'RPG',
       'Battle Royale', 'Fitness', 'Racing', 'Lightgun Shooter', 'Party',
       'FPS', 'Sim', 'Fighting', 'Action', 'Action RPG', 'Puzzle',
       'Racing Sim', 'Life Sim'], dtype=object)

In [48]:
genre_df = pd.DataFrame(genre_list)
genre_df.columns=['genre']
genre_df

               genre
0            Sandbox
1   Action Adventure
2             Sports
3         Platformer
4                RPG
5      Battle Royale
6            Fitness
7             Racing
8   Lightgun Shooter
9              Party
10               FPS
11               Sim
12          Fighting
13            Action
14        Action RPG
15            Puzzle
16        Racing Sim
17          Life Sim