In [1]:
import pandas as pd
import numpy as np
from scipy import array, concatenate
from bs4 import BeautifulSoup as bs
from webdriver_manager.chrome import ChromeDriverManager
import requests
import os
from sqlalchemy import create_engine
import numpy as np
import matplotlib.pyplot as plt
import psycopg2

In [2]:
rds_connection_string = "postgres:group2@35.224.199.242:5432/postgres"
engine = create_engine(f'postgresql://{rds_connection_string}')

In [3]:
conn = engine.connect()

In [4]:
engine.table_names()

C:\Users\malac\AppData\Local\Temp/ipykernel_23992/4162273999.py:1: SADeprecationWarning: The Engine.table_names() method is deprecated and will be removed in a future release.  Please refer to Inspector.get_table_names(). (deprecated since: 1.4)
  engine.table_names()

['GameGenres',
 'GamesReleasedPlatforms',
 'videogames',
 'genre_junc',
 'platform_junc',
 'genre_id',
 'platforms',
 'all_games']

In [12]:
csv_path = ("C:/Users/malac/SMU/Project 2/Malachai Work/genre.csv")
genre_df = pd.read_csv(csv_path)
genre_df

                   0
0            Sandbox
1   Action Adventure
2             Sports
3         Platformer
4                RPG
5      Battle Royale
6            Fitness
7             Racing
8   Lightgun Shooter
9              Party
10               FPS
11               Sim
12          Fighting
13            Action
14        Action RPG
15            Puzzle
16        Racing Sim
17          Life Sim
18          Platform
19      Role-Playing
20              Misc
21           Shooter
22        Simulation
23         Adventure
24          Strategy

In [17]:
genre_df = genre_df.rename({'0': 'genre'}, axis=1)
genre_df

               genre
0            Sandbox
1   Action Adventure
2             Sports
3         Platformer
4                RPG
5      Battle Royale
6            Fitness
7             Racing
8   Lightgun Shooter
9              Party
10               FPS
11               Sim
12          Fighting
13            Action
14        Action RPG
15            Puzzle
16        Racing Sim
17          Life Sim
18          Platform
19      Role-Playing
20              Misc
21           Shooter
22        Simulation
23         Adventure
24          Strategy

In [22]:
genre_df.reset_index(drop=False)

    index             genre
0       0           Sandbox
1       1  Action Adventure
2       2            Sports
3       3        Platformer
4       4               RPG
5       5     Battle Royale
6       6           Fitness
7       7            Racing
8       8  Lightgun Shooter
9       9             Party
10     10               FPS
11     11               Sim
12     12          Fighting
13     13            Action
14     14        Action RPG
15     15            Puzzle
16     16        Racing Sim
17     17          Life Sim
18     18          Platform
19     19      Role-Playing
20     20              Misc
21     21           Shooter
22     22        Simulation
23     23         Adventure
24     24          Strategy

In [24]:
genre_df = genre_df.rename({'index': 'genre_ID'}, axis=columns)
genre_df

NameError: name 'columns' is not defined